# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  midearth-benchmarks:
    dependencies:
    - base
    - midearth
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: midearth is a new Haskeleton package.
executables:
  midearth:
    dependencies:
    - base
    - midearth
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: thealexgraham/midearth
library:
  dependencies:
  - base
  - hosc <= 0.15 && >= 0.15
  - hosc-utils <= 0.15 && >= 0.15
  source-dirs: library
license: MIT
maintainer: Alex Graham
name: midearth
synopsis: A new Haskeleton package.
tests:
  midearth-test-suite:
    dependencies:
    - base
    - midearth
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
